print("Pilih Lirik Lagu")
print("1 Untuk Shadow Shadow Oleh Azari")
print("2 Untuk Carnivorous Plant Oleh Rim")
print("3 Untuk Eye Oleh Kanaria")
print("4 Untuk Mango From Wrist Oleh Takayan")
print("5 Untuk He Cheated On Me Oleh Riria")
print("6 Untuk Tamaya Oleh Chinozo")

pilihan = input("Masukkan Pilihan Lirik Lagu(1/2/3/4/5/6): ")

if pilihan == '1' :
    print("Shadow Shadow")
    print("Dinyanyikan Oleh Azari")
    print("Hitoshirezu naita urahara na Lie")
    print("Warui no wa sai ka shiruyoshi mo nai")
    print("Utagai no taika kono mi de gitai")
    print("Kodoku da Shadow Shadow")
    print("")
    print("Machikado nite akuma ni tamashii wo Sell")
    print("Abaite kuwazu tomo nakami wa Null")
    print("Egao de hodashitara mayowazu Kill")
    print("Kodoku na Shadow Shadow")
    print("")
    print("Kurayami wo terashita tsumasaki nya Hell")
    print("Mayoi mo shinai sono atama wa Ill")
    print("Gomakashi no kai ni kamae tsutsu Chill")
    print("Kodoku na Shadow Shadow")
    print("")
    print("Tarinai")
    print("Zarazara no ai kemureba amai")
    print("Koyoi mo haiena wa kari no you")
    print("Kao mo shiranai seija no ratai")
    print("Sasu oto ni you")
    print("")
    print("Oodaa")
    print("Ego no jareai tsubuse jubunairu")
    print("Itami ga kairaku ni kawaru koro")
    print("Kikoeru darou")
    print("Suterareta kage ga odoru baraddo")
    print("")
    print("Machikado nite akuma ni tamashii wo Sell")
    print("Abaite kuwazu tomo nakami wa Null")
    print("Egao de hodashitara mayowazu Kill")
    print("Kodoku na Shadow Shadow")
    print("")
    print("Kurayami wo terashita tsumasaki nya Hell")
    print("Mayoi mo shinai sono atama wa Ill")
    print("Gomakashi no kai ni kamae tsutsu Chill")
    print("Kodoku na Shadow Shadow")
    print("")
    print("Kawa wo hagitotta naka wo mite Sigh")
    print("Munashisa kakushite tsumiagaru hai")
    print("Namari ni somatta migite ga itai")
    print("Kodoku da Shadow Shadow")
    print("")
if pilihan == '2' :
    print("Canivorous Plant")
    print("Dinyanyikan Oleh Rim")
    print("")
elif pilihan == '3' :
    print("Eye")
    print("Dinyanyikan Oleh Kanaria")
    print("")
elif pilihan == '4' :
    print("Mango From Wrist")
    print("Dinyanyikan Oleh Takayan")
    print("")
elif pilihan == '5' :
    print("He Cheated On Me")
    print("Dinyanyikan Oleh Riria")
    print("")
elif pilihan == '6' :
    print("Tamaya")
    print("Dinyanyikan Oleh Chinozo")
    print("")
else:
    print("Pilihan Tidak Valid")
